services:
  - type: web
    name: text-scanner-ocr
    env: docker
    plan: standard
    envVars:
      - key: PORT
        value: 8000
      - key: PADDLE_HOME
        value: /app/paddleocr
      - key: RENDER_ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    buildFilter:
      ignoredPaths:
        - "**/__pycache__/**"
        - "myra-ocr/**"
        - ".env*"
        - "*.log"
